name: Release

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  save-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: git clone
        run: git clone --depth 1 https://github.com/volcano-sh/volcano.git
      - name: make images
        run: cd volcano; make images
      - name: list images
        run: docker images
